import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { AppShell, Button, Header } from "@mantine/core";
import { useReadRemindersMeRemindersMeGet, useSayHelloHelloNameGet } from "@/api/default/default";
import { useLiff } from "@/libs/liff";
import ReminderList from "@/components/ReminderList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const name = useSayHelloHelloNameGet("World", {
    query: {
      suspense: true,
    },
  });
  const liff = useLiff();
  const reminders = useReadRemindersMeRemindersMeGet(undefined, { query: { suspense: true } });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppShell
          header={
            <Header height={60}>
              <HeaderContent />
            </Header>
          }
        >
          <ReminderList />
          {/* @ts-ignore*/}
          <p>name.data: {name.data?.message}</p>
          <Button
            onClick={() => {
              liff?.login();
            }}
          >
            {liff?.isLoggedIn() ? `Logout` : "Login"}
          </Button>
          <p>token:{liff?.getAccessToken()}</p>
          <p>liffOrError: {liff != null ? liff.id : "not yet loaded"}</p>
          <p>reminders: {JSON.stringify(reminders.data)}</p>
        </AppShell>
      </main>
    </>
  );
}

const HeaderContent = () => {
  return <div>header</div>;
};
