/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface HeroRead {
  name: string;
  secret_name: string;
  age?: number;
  id: number;
}
