/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ReminderRead {
  line_to: string;
  name: string;
  time: string;
  id: number;
}
